// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moczxroojvdjevnorfiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vY3p4cm9vanZkamV2bm9yZml5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDg0MjgsImV4cCI6MjA2Nzg4NDQyOH0.h1x_Zr5zfJYiCDQx9ugohRUxZ-qg1K8Wf5sGYmjNHnM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});