// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blvcxbqqqjdhvrkgondd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsdmN4YnFxcWpkaHZya2dvbmRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTIzMzcsImV4cCI6MjA2MjgyODMzN30.CyTLwO7CUTpBMIPvGmofObuWLqQlIxgKsxnaHqZQkW8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});